/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Tasky API
 * Auth and Users API
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDto } from './userResponseDto';

export interface AuthResponseDto {
  user: UserResponseDto;
  accessToken: string;
  refreshToken: string;
}
