/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Tasky API
 * Auth and Users API
 * OpenAPI spec version: 1.0
 */

export interface UserResponseDto {
  id: string;
  /** @nullable */
  name: string | null;
  email: string;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
